ebean:
  development:
    migration:
      run: true
  production:
    migration:
      run: true
datasource:
    db:
        username: ""
        password: ""
        url: "jdbc:h2:./hexlet"
    production:
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}
      url: ${JDBC_DATABASE_URL}
